##############################################################################
# VoiceCode, a programming-by-voice environment
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# (C)2000, National Research Council of Canada
#
##############################################################################

#############################################################################
# Abbreviations needed for compiling public symbols of C/C++ standard
# libraries
#############################################################################

add_alt_abbreviations('A. cos', ['acos'])
add_alt_abbreviations('arc cosine', ['acos'])
add_alt_abbreviations('arc cos', ['acos'])
add_alt_abbreviations('A. sine', ['asin'])
add_alt_abbreviations('arc sine', ['asin'])
add_alt_abbreviations('ascii time', ['asctime'])
add_alt_abbreviations('ask time', ['asctime'])
add_alt_abbreviations('at exit',['atexit'])
add_alt_abbreviations('A. to I.', ['atoi'])
add_alt_abbreviations('Boole alpha',['boolalpha']) #: appears in ['boolalpha']
add_alt_abbreviations('Boolean alpha',['boolalpha']) #: appears in ['boolalpha']
add_alt_abbreviations('B. search',['bsearch']) #: appears in ['bsearch']
add_alt_abbreviations('buff size',['bufsiz']) #: appears in ['BUFSIZ']
add_alt_abbreviations('buffer size',['bufsiz']) #: appears in ['BUFSIZ']
add_alt_abbreviations('C. Alloc',['calloc']) #: appears in ['calloc']
add_alt_abbreviations('Cal lock',['calloc']) #: appears in ['calloc']
add_alt_abbreviations('C. error',['cerr']) #: appears in ['cerr']
add_alt_abbreviations('clear error',['clearerr']) #: appears in ['clearerr']
add_alt_abbreviations('clock type',['clock_t'])
add_alt_abbreviations('copy format',['copyfmt']) #: appears in ['copyfmt']
add_alt_abbreviations('copy F. M. T.',['copyfmt']) #: appears in ['copyfmt']
add_alt_abbreviations('C. time',['ctime']) #: appears in ['ctime']
add_alt_abbreviations('C. type',['ctype']) #: appears in ['LC_CTYPE', 'ctype']
add_alt_abbreviations('diff time',['difftime']) #: appears in ['difftime']
add_alt_abbreviations('div type',['div_t'])
add_alt_abbreviations('E. back',['eback']) #: appears in ['eback']
add_alt_abbreviations('E. convert',['ecvt']) #: appears in ['ecvt']
add_alt_abbreviations('E. get pointer',['egptr']) #: appears in ['egptr']
add_alt_abbreviations('end get pointer',['egptr']) #: appears in ['egptr']
add_alt_abbreviations('E. G. pointer',['egptr']) #: appears in ['egptr']
add_alt_abbreviations('egg pointer',['egptr']) #: appears in ['egptr']
add_alt_abbreviations('E. put pointer',['epptr']) #: appears in ['epptr']
add_alt_abbreviations('end put pointer',['epptr']) #: appears in ['epptr']
add_alt_abbreviations('E. P. pointer',['epptr']) #: appears in ['epptr']
add_alt_abbreviations('E. range',['erange']) #: appears in ['ERANGE']
add_alt_abbreviations('error range',['erange']) #: appears in ['ERANGE']
add_alt_abbreviations('error no',['errno']) #: appears in ['errno']
add_alt_abbreviations('error number',['errno']) #: appears in ['errno']
add_alt_abbreviations('F. close',['fclose']) #: appears in ['fclose']
add_alt_abbreviations('file close',['fclose']) #: appears in ['fclose']
add_alt_abbreviations('F. convert',['fcvt']) #: appears in ['fcvt']
add_alt_abbreviations('F. E. O. F.',['feof']) #: appears in ['feof']
add_alt_abbreviations('file E. O. F.',['feof']) #: appears in ['feof']
add_alt_abbreviations('file end of file',['feof']) #: appears in ['feof']
add_alt_abbreviations('F. end of file',['feof']) #: appears in ['feof']
add_alt_abbreviations('F. error',['ferror']) #: appears in ['ferror']
add_alt_abbreviations('file error',['ferror']) #: appears in ['ferror']
add_alt_abbreviations('F. flush',['fflush']) #: appears in ['fflush']
add_alt_abbreviations('file flush',['fflush']) #: appears in ['fflush']
add_alt_abbreviations('F. get C.',['fgetc']) #: appears in ['fgetc']
add_alt_abbreviations('file get C.',['fgetc']) #: appears in ['fgetc']
add_alt_abbreviations('file get character',['fgetc']) #: appears in ['fgetc']
add_alt_abbreviations('F. get pause',['fgetpos']) #: appears in ['fgetpos']
add_alt_abbreviations('F. get position',['fgetpos']) #: appears in ['fgetpos']
add_alt_abbreviations('file get pause',['fgetpos']) #: appears in ['fgetpos']
add_alt_abbreviations('file get position',['fgetpos']) #: appears in ['fgetpos']
add_alt_abbreviations('F. gets',['fgets']) #: appears in ['fgets']
add_alt_abbreviations('F. get S.',['fgets']) #: appears in ['fgets']
add_alt_abbreviations('file gets',['fgets']) #: appears in ['fgets']
add_alt_abbreviations('file get S.',['fgets']) #: appears in ['fgets']
add_alt_abbreviations('file get S.',['fgets']) #: appears in ['fgets']
add_alt_abbreviations('F. get string',['fgets']) #: appears in ['fgets']
add_alt_abbreviations('file get string',['fgets']) #: appears in ['fgets']
add_alt_abbreviations('file buff',['filebuf']) #: appears in ['filebuf']
add_alt_abbreviations('file buffer',['filebuf']) #: appears in ['filebuf']
add_alt_abbreviations('F. mod',['fmod']) #: appears in ['fmod']
add_alt_abbreviations('float mod',['fmod']) #: appears in ['fmod']
add_alt_abbreviations('float modulo',['fmod']) #: appears in ['fmod']
add_alt_abbreviations('F. M. T. flags',['fmtflags']) #: appears in ['fmtflags']
add_alt_abbreviations('format flags',['fmtflags']) #: appears in ['fmtflags']
add_alt_abbreviations('F. pause',['fpos']) #: appears in ['fpos_t']
add_alt_abbreviations('file pause',['fpos']) #: appears in ['fpos_t']
add_alt_abbreviations('F. position',['fpos']) #: appears in ['fpos_t']
add_alt_abbreviations('F. pause type',['fpos_t']) #: appears in ['fpos_t']
add_alt_abbreviations('file pause type',['fpos_t']) #: appears in ['fpos_t']
add_alt_abbreviations('F. position type',['fpos_t']) #: appears in ['fpos_t']
add_alt_abbreviations('F. put C.',['fputc']) #: appears in ['fputc']
add_alt_abbreviations('file put C.',['fputc']) #: appears in ['fputc']
add_alt_abbreviations('file put character',['fputc']) #: appears in ['fputc']
add_alt_abbreviations('F. put char',['fputchar']) #: appears in ['fputchar']
add_alt_abbreviations('file put char',['fputchar']) #: appears in ['fputchar']
add_alt_abbreviations('file put character',['fputchar']) #: appears in ['fputchar']
add_alt_abbreviations('F. puts',['fputs']) #: appears in ['fputs']
add_alt_abbreviations('F. put S.',['fputs']) #: appears in ['fputs']
add_alt_abbreviations('file put S.',['fputs']) #: appears in ['fputs']
add_alt_abbreviations('file put string',['fputs']) #: appears in ['fputs']
######################add_alt_abbreviations('',['frac']): appears in ['frac_digits', 'int_frac_digits']
add_alt_abbreviations('F. print F.',['fprintf']) #: appears in ['fprintf']
add_alt_abbreviations('file print F.',['fprintf']) #: appears in ['fprintf']
add_alt_abbreviations('F. print format',['fprintf']) #: appears in ['fprintf']
add_alt_abbreviations('file print format',['fprintf']) #: appears in ['fprintf']
add_alt_abbreviations('file read',['fread']) #: appears in ['fread']
add_alt_abbreviations('free open',['freopen']) #: appears in ['freopen']
add_alt_abbreviations('F. reopen',['freopen']) #: appears in ['freopen']
add_alt_abbreviations('file reopen',['freopen']) #: appears in ['freopen']
add_alt_abbreviations('fur exp',['frexp']) #: appears in ['frexp']
add_alt_abbreviations('F. R. E. X. P.',['frexp']) #: appears in ['frexp']
add_alt_abbreviations('float remainder exponent',['frexp']) #: appears in ['frexp']
add_alt_abbreviations('F. scan F.',['fscanf']) #: appears in ['fscanf']
add_alt_abbreviations('file scan F.',['fscanf']) #: appears in ['fscanf']
add_alt_abbreviations('file scan format',['fscanf']) #: appears in ['fscanf']
add_alt_abbreviations('F. seek',['fseek']) #: appears in ['fseek']
add_alt_abbreviations('file seek',['fseek']) #: appears in ['fseek']
add_alt_abbreviations('F. set pause',['fsetpos']) #: appears in ['fsetpos']
add_alt_abbreviations('file set pause',['fsetpos']) #: appears in ['fsetpos']
add_alt_abbreviations('file set position',['fsetpos']) #: appears in ['fsetpos']
add_alt_abbreviations('F. tell',['ftell']) #: appears in ['ftell']
add_alt_abbreviations('file tell',['ftell']) #: appears in ['ftell']
add_alt_abbreviations('F. write',['fwrite']) #: appears in ['fwrite']
add_alt_abbreviations('file write',['fwrite']) #: appears in ['fwrite']
add_alt_abbreviations('G. bump',['gbump']) #: appears in ['gbump']
add_alt_abbreviations('get bump',['gbump']) #: appears in ['gbump']
add_alt_abbreviations('G. count',['gcount']) #: appears in ['gcount']
add_alt_abbreviations('get count',['gcount']) #: appears in ['gcount']
add_alt_abbreviations('G. C. V. T.',['gcvt']) #: appears in ['gcvt']
add_alt_abbreviations('G. convert',['gcvt']) #: appears in ['gcvt']
add_alt_abbreviations('get C.',['getc']) #: appears in ['getc']
add_alt_abbreviations('get char',['getchar']) #: appears in ['getchar']
add_alt_abbreviations('get character',['getchar']) #: appears in ['getchar']
add_alt_abbreviations('get env',['getenv']) #: appears in ['getenv']
add_alt_abbreviations('get E. N. V.',['getenv']) #: appears in ['getenv']
add_alt_abbreviations('get environment',['getenv']) #: appears in ['getenv']
add_alt_abbreviations('get line',['getline']) #: appears in ['getline']
add_alt_abbreviations('get LOC',['getloc']) #: appears in ['getloc']
add_alt_abbreviations('get locale',['getloc']) #: appears in ['getloc']
add_alt_abbreviations('get W.',['getw']) #: appears in ['getw']
add_alt_abbreviations('G. M. time',['gmtime']) #: appears in ['gmtime']
add_alt_abbreviations('Greenwich mean time',['gmtime']) #: appears in ['gmtime']
add_alt_abbreviations('G. pointer',['gptr']) #: appears in ['gptr']
add_alt_abbreviations('get pointer',['gptr']) #: appears in ['gptr']
add_alt_abbreviations('H.',['h']) #: appears in ['h']
add_alt_abbreviations('if stream',['ifstream']) #: appears in ['ifstream']
add_alt_abbreviations('I. F. stream',['ifstream']) #: appears in ['ifstream']
add_alt_abbreviations('input F. stream',['ifstream']) #: appears in ['ifstream']
add_alt_abbreviations('input file stream',['ifstream']) #: appears in ['ifstream']
add_alt_abbreviations('S. I. G.',['sig']) #: appears in ['SIG_IGN']
add_alt_abbreviations('sig',['sig']) #: appears in ['SIG_IGN']
add_alt_abbreviations('I. G. N.',['ign']) #: appears in ['SIG_IGN']
add_alt_abbreviations('ignore',['ign']) #: appears in ['SIG_IGN']
add_alt_abbreviations('in place',['inplace']) #: appears in ['inplace_merge']
add_alt_abbreviations('I. O. F. B. F.',['iofbf']) #: appears in ['_IOFBF']
add_alt_abbreviations('I. O. full buff',['iofbf']) #: appears in ['_IOFBF']
add_alt_abbreviations('I. O. fully buffered',['iofbf']) #: appears in ['_IOFBF']
add_alt_abbreviations('I. O. state',['iostate']) #: appears in ['iostate']
add_alt_abbreviations('is Al numb',['isalnum']) #: appears in ['isalnum']
add_alt_abbreviations('is alphanumeric',['isalnum']) #: appears in ['isalnum']
add_alt_abbreviations('is alpha',['isalpha']) #: appears in ['isalpha']
add_alt_abbreviations('is alphabetic',['isalpha']) #: appears in ['isalpha']
add_alt_abbreviations('is control',['iscntrl']) #: appears in ['iscntrl']
add_alt_abbreviations('is digit',['isdigit']) #: appears in ['isdigit']
add_alt_abbreviations('is D. S. T.',['isdst']) #: appears in ['tm_isdst']
add_alt_abbreviations('is daylight savings time',['isdst']) #: appears in ['tm_isdst']
add_alt_abbreviations('is graph',['isgraph']) #: appears in ['isgraph']
add_alt_abbreviations('is graphical',['isgraph']) #: appears in ['isgraph']
add_alt_abbreviations('is lower',['islower']) #: appears in ['islower']
add_alt_abbreviations('is lowercase',['islower']) #: appears in ['islower']
add_alt_abbreviations('is print',['isprint']) #: appears in ['isprint']
add_alt_abbreviations('is printable',['isprint']) #: appears in ['isprint']
add_alt_abbreviations('is punked',['ispunct']) #: appears in ['ispunct']
add_alt_abbreviations('is punctuation',['ispunct']) #: appears in ['ispunct']
add_alt_abbreviations('is space',['isspace']) #: appears in ['isspace']
add_alt_abbreviations('I. string stream',['istringstream']) #: appears in ['istringstream']
add_alt_abbreviations('input string stream',['istringstream']) #: appears in ['istringstream']
add_alt_abbreviations('is upper',['isupper']) #: appears in ['isupper']
add_alt_abbreviations('is uppercase',['isupper']) #: appears in ['isupper']
add_alt_abbreviations('is X. digit',['isxdigit']) #: appears in ['isxdigit']
add_alt_abbreviations('is hex digit',['isxdigit']) #: appears in ['isxdigit']
add_alt_abbreviations('is hexadecimal digit',['isxdigit']) #: appears in ['isxdigit']
add_alt_abbreviations('I. to A.',['itoa']) #: appears in ['itoa']
add_alt_abbreviations('I. word',['iword']) #: appears in ['iword']
add_alt_abbreviations('integer word',['iword']) #: appears in ['iword']
add_alt_abbreviations('L.',['l']) #: appears in ['L_tmpnam']
add_alt_abbreviations('length',['l']) #: appears in ['L_tmpnam']
add_alt_abbreviations('L. conv',['lconv']) #: appears in ['lconv']
add_alt_abbreviations('locale conventions',['lconv']) #: appears in ['lconv']
add_alt_abbreviations('L. D. B. L. ',['ldbl']) #: appears in ['LDBL_DIG', 'LDBL_EPSILON', 'LDBL_MANT_DIG', 'LDBL_MAX', 'LD
add_alt_abbreviations('L. double',['ldbl']) #: appears in ['LDBL_DIG', 'LDBL_EPSILON', 'LDBL_MANT_DIG', 'LDBL_MAX', 'LD
add_alt_abbreviations('long double',['ldbl']) #: appears in ['LDBL_DIG', 'LDBL_EPSILON', 'LDBL_MANT_DIG', 'LDBL_MAX', 'LDBL_MAX_EXP', '])LDBL_MIN', 'LDBL_MIN_EXP']
add_alt_abbreviations('L. D. E. X. P.',['ldexp']) #: appears in ['ldexp']
add_alt_abbreviations('L. D. exp',['ldexp']) #: appears in ['ldexp']
add_alt_abbreviations('L. double E. X. P.',['ldexp']) #: appears in ['ldexp']
add_alt_abbreviations('L. double exp',['ldexp']) #: appears in ['ldexp']
add_alt_abbreviations('load double E. X. P.',['ldexp']) #: appears in ['ldexp']
add_alt_abbreviations('load double exp',['ldexp']) #: appears in ['ldexp']
add_alt_abbreviations('L. div',['ldiv']) #: appears in ['ldiv', 'ldiv_t']
add_alt_abbreviations('L. divide',['ldiv']) #: appears in ['ldiv', 'ldiv_t']
add_alt_abbreviations('long div',['ldiv']) #: appears in ['ldiv', 'ldiv_t']
add_alt_abbreviations('long divide',['ldiv']) #: appears in ['ldiv', 'ldiv_t']
add_alt_abbreviations('L. div type',['ldiv_t']) #: appears in ['ldiv', 'ldiv_t']
add_alt_abbreviations('L. divide type',['ldiv_t']) #: appears in ['ldiv', 'ldiv_t']
add_alt_abbreviations('long div type',['ldiv_t']) #: appears in ['ldiv', 'ldiv_t']
add_alt_abbreviations('long divide type',['ldiv_t']) #: appears in ['ldiv', 'ldiv_t']
add_alt_abbreviations('lexicographic',['lexicographical']) #: appears in ['lexicographical_compare']
add_alt_abbreviations('L. find',['lfind']) #: appears in ['lfind']
add_alt_abbreviations('linear find',['lfind']) #: appears in ['lfind']
add_alt_abbreviations('locale conv',['localeconv']) #: appears in ['localeconv']
add_alt_abbreviations('locale conventions',['localeconv']) #: appears in ['localeconv']
add_alt_abbreviations('local time',['localtime']) #: appears in ['localtime']
add_alt_abbreviations('long jump',['longjmp']) #: appears in ['longjmp']
add_alt_abbreviations('L. search',['lsearch']) #: appears in ['lsearch']
add_alt_abbreviations('linear search',['lsearch']) #: appears in ['lsearch']
add_alt_abbreviations('L. to A.',['ltoa']) #: appears in ['ltoa']
add_alt_abbreviations('mantissa',['mant']) #: appears in ['DBL_MANT_DIG', 'FLT_MANT_DIG', 'LDBL_MANT_DIG']
add_alt_abbreviations('M. day',['mday']) #: appears in ['tm_mday']
add_alt_abbreviations('month day',['mday']) #: appears in ['tm_mday']
add_alt_abbreviations('mem Chir',['memchr']) #: appears in ['memchr']
add_alt_abbreviations('memory char',['memchr']) #: appears in ['memchr']
add_alt_abbreviations('memory character',['memchr']) #: appears in ['memchr']
add_alt_abbreviations('mem comp',['memcmp']) #: appears in ['memcmp']
add_alt_abbreviations('mem compare',['memcmp']) #: appears in ['memcmp']
add_alt_abbreviations('memory compare',['memcmp']) #: appears in ['memcmp']
add_alt_abbreviations('memory comp',['memcmp']) #: appears in ['memcmp']
add_alt_abbreviations('mem move',['memmove']) #: appears in ['memmove']
add_alt_abbreviations('memory move',['memmove']) #: appears in ['memmove']
add_alt_abbreviations('M. K. time',['mktime']) #: appears in ['mktime']
add_alt_abbreviations('make time',['mktime']) #: appears in ['mktime']
add_alt_abbreviations('mod F.',['modf']) #: appears in ['modf']
add_alt_abbreviations('mod float',['modf']) #: appears in ['modf']
add_alt_abbreviations('modulo float',['modf']) #: appears in ['modf']
add_alt_abbreviations('N.',['n']) #: appears in ['fill_n', 'generate_n', 'n_cs_precedes', 'n_sep_by_space', 'n_sign_posn', '])search_n']
add_alt_abbreviations('no Boole alpha',['noboolalpha']) #: appears in ['noboolalpha']
add_alt_abbreviations('no Boolean alpha',['noboolalpha']) #: appears in ['noboolalpha']
add_alt_abbreviations('no show base',['noshowbase']) #: appears in ['noshowbase']
add_alt_abbreviations('no show point',['noshowpoint']) #: appears in ['noshowpoint']
add_alt_abbreviations('no show pause',['noshowpos']) #: appears in ['noshowpos']
add_alt_abbreviations('no show position',['noshowpos']) #: appears in ['noshowpos']
add_alt_abbreviations('no skip W. S.',['noskipws']) #: appears in ['noskipws']
add_alt_abbreviations('no skip white space',['noskipws']) #: appears in ['noskipws']
add_alt_abbreviations('no unit buff',['nounitbuf']) #: appears in ['nounitbuf']
add_alt_abbreviations('no unit buffer',['nounitbuf']) #: appears in ['nounitbuf']
add_alt_abbreviations('no uppercase',['nouppercase']) #: appears in ['nouppercase']
add_alt_abbreviations('offset of',['offsetof']) #: appears in ['offsetof']
add_alt_abbreviations('O. F. stream',['ofstream']) #: appears in ['ofstream']
add_alt_abbreviations('O. file stream',['ofstream']) #: appears in ['ofstream']
add_alt_abbreviations('output F. stream',['ofstream']) #: appears in ['ofstream']
add_alt_abbreviations('output file stream',['ofstream']) #: appears in ['ofstream']
add_alt_abbreviations('open mode',['openmode']) #: appears in ['openmode']
add_alt_abbreviations('O. string stream',['ostringstream']) #: appears in ['ostringstream']
add_alt_abbreviations('output string stream',['ostringstream']) #: appears in ['ostringstream']
add_alt_abbreviations('P.',['p']) #: appears in ['p_cs_precedes', 'p_sep_by_space', 'p_sign_posn']
add_alt_abbreviations('P. back fail',['pbackfail']) #: appears in ['pbackfail']
add_alt_abbreviations('put back fail',['pbackfail']) #: appears in ['pbackfail']
add_alt_abbreviations('P. base',['pbase']) #: appears in ['pbase']
add_alt_abbreviations('put base',['pbase']) #: appears in ['pbase']
add_alt_abbreviations('P. bump',['pbump']) #: appears in ['pbump']
add_alt_abbreviations('put bump',['pbump']) #: appears in ['pbump']
add_alt_abbreviations('P. error',['perror']) #: appears in ['perror']
add_alt_abbreviations('put error',['perror']) #: appears in ['perror']
# add_alt_abbreviations('position',['posn']): appears in ['n_sign_posn', 'p_sign_posn']
add_alt_abbreviations('P. pointer',['pptr']) #: appears in ['pptr']
add_alt_abbreviations('put pointer',['pptr']) #: appears in ['pptr']
# add_alt_abbreviations('',['prev']): appears in ['prev_permutation']
add_alt_abbreviations('pointer diff',['ptrdiff']) #: appears in ['ptrdiff_t']
add_alt_abbreviations('pointer diff type',['ptrdiff_t']) #: appears in ['ptrdiff_t']
add_alt_abbreviations('pub imbue',['pubimbue']) #: appears in ['pubimbue']
add_alt_abbreviations('public imbue',['pubimbue']) #: appears in ['pubimbue']
add_alt_abbreviations('pub seek off',['pubseekoff']) #: appears in ['pubseekoff']
add_alt_abbreviations('pub seek offset',['pubseekoff']) #: appears in ['pubseekoff']
add_alt_abbreviations('public seek off',['pubseekoff']) #: appears in ['pubseekoff']
add_alt_abbreviations('public seek offset',['pubseekoff']) #: appears in ['pubseekoff']
add_alt_abbreviations('pub seek pause',['pubseekpos']) #: appears in ['pubseekpos']
add_alt_abbreviations('public seek pause',['pubseekpos']) #: appears in ['pubseekpos']
add_alt_abbreviations('pub seek position',['pubseekpos']) #: appears in ['pubseekpos']
add_alt_abbreviations('public seek position',['pubseekpos']) #: appears in ['pubseekpos']
add_alt_abbreviations('pub set buff',['pubsetbuf']) #: appears in ['pubsetbuf']
add_alt_abbreviations('pub set buffer',['pubsetbuf']) #: appears in ['pubsetbuf']
add_alt_abbreviations('public set buff',['pubsetbuf']) #: appears in ['pubsetbuf']
add_alt_abbreviations('public set buffer',['pubsetbuf']) #: appears in ['pubsetbuf']
add_alt_abbreviations('pub sync',['pubsync']) #: appears in ['pubsync']
add_alt_abbreviations('public sync',['pubsync']) #: appears in ['pubsync']
add_alt_abbreviations('put back',['putback']) #: appears in ['putback']
add_alt_abbreviations('put C.',['putc']) #: appears in ['putc']
add_alt_abbreviations('put char',['putchar']) #: appears in ['putchar']
add_alt_abbreviations('put character',['putchar']) #: appears in ['putchar']
add_alt_abbreviations('put env',['putenv']) #: appears in ['putenv']
add_alt_abbreviations('put environment',['putenv']) #: appears in ['putenv']
add_alt_abbreviations('put W.',['putw']) #: appears in ['putw']
add_alt_abbreviations('P. word',['pword']) #: appears in ['pword']
add_alt_abbreviations('pointer word',['pword']) #: appears in ['pword']
add_alt_abbreviations('quotient',['quot']) #: appears in ['quot']
add_alt_abbreviations('read buff',['rdbuf']) #: appears in ['rdbuf']
add_alt_abbreviations('read buffer',['rdbuf']) #: appears in ['rdbuf']
add_alt_abbreviations('read state',['rdstate']) #: appears in ['rdstate']
add_alt_abbreviations('read some',['readsome']) #: appears in ['readsome']
add_alt_abbreviations('S. bump C.',['sbumpc']) #: appears in ['sbumpc']
add_alt_abbreviations('stream bump C.',['sbumpc']) #: appears in ['sbumpc']
add_alt_abbreviations('S. bump char',['sbumpc']) #: appears in ['sbumpc']
add_alt_abbreviations('stream bump char',['sbumpc']) #: appears in ['sbumpc']
add_alt_abbreviations('S. char',['schar']) #: appears in ['SCHAR_MAX', 'SCHAR_MIN']
add_alt_abbreviations('S. character',['schar']) #: appears in ['SCHAR_MAX', 'SCHAR_MIN']
add_alt_abbreviations('signed char',['schar']) #: appears in ['SCHAR_MAX', 'SCHAR_MIN']
add_alt_abbreviations('signed character',['schar']) #: appears in ['SCHAR_MAX', 'SCHAR_MIN']
add_alt_abbreviations('seek dir',['seekdir']) #: appears in ['seekdir']
add_alt_abbreviations('seek directory',['seekdir']) #: appears in ['seekdir']
add_alt_abbreviations('seek G.',['seekg']) #: appears in ['seekg']
add_alt_abbreviations('seek get',['seekg']) #: appears in ['seekg']
add_alt_abbreviations('seek off',['seekoff']) #: appears in ['seekoff']
add_alt_abbreviations('seek offset',['seekoff']) #: appears in ['seekoff']
add_alt_abbreviations('seek P.',['seekp']) #: appears in ['seekp']
add_alt_abbreviations('seek put',['seekp']) #: appears in ['seekp']
add_alt_abbreviations('seek pause',['seekpos']) #: appears in ['seekpos']
add_alt_abbreviations('seek position',['seekpos']) #: appears in ['seekpos']
add_alt_abbreviations('set buf',['setbuf']) #: appears in ['setbuf']
add_alt_abbreviations('set buffer',['setbuf']) #: appears in ['setbuf']
add_alt_abbreviations('set F.',['setf']) #: appears in ['setf']
add_alt_abbreviations('set format',['setf']) #: appears in ['setf']
add_alt_abbreviations('set flag',['setf']) #: appears in ['setf']
add_alt_abbreviations('set G.',['setg']) #: appears in ['setg']
add_alt_abbreviations('set get',['setg']) #: appears in ['setg']
add_alt_abbreviations('set jump',['setjmp']) #: appears in ['setjmp']
add_alt_abbreviations('set locale',['setlocale']) #: appears in ['setlocale']
add_alt_abbreviations('set P.',['setp']) #: appears in ['setp']
add_alt_abbreviations('set put',['setp']) #: appears in ['setp']
add_alt_abbreviations('set state',['setstate']) #: appears in ['setstate']
add_alt_abbreviations('set V. buff',['setvbuf']) #: appears in ['setvbuf']
add_alt_abbreviations('set V. buffer',['setvbuf']) #: appears in ['setvbuf']
add_alt_abbreviations('S. get C.',['sgetc']) #: appears in ['sgetc']
add_alt_abbreviations('S. get char',['sgetc']) #: appears in ['sgetc']
add_alt_abbreviations('stream get C.',['sgetc']) #: appears in ['sgetc']
add_alt_abbreviations('stream get char',['sgetc']) #: appears in ['sgetc']
add_alt_abbreviations('S. get N.',['sgetn']) #: appears in ['sgetn']
add_alt_abbreviations('stream get N.',['sgetn']) #: appears in ['sgetn']
add_alt_abbreviations('show base',['showbase']) #: appears in ['showbase']
add_alt_abbreviations('show many C.',['showmanyc']) #: appears in ['showmanyc']
add_alt_abbreviations('show many char',['showmanyc']) #: appears in ['showmanyc']
add_alt_abbreviations('show point',['showpoint']) #: appears in ['showpoint']
add_alt_abbreviations('show pause',['showpos']) #: appears in ['showpos']
add_alt_abbreviations('show position',['showpos']) #: appears in ['showpos']
add_alt_abbreviations('shirt',['shrt']) #: appears in ['SHRT_MAX', 'SHRT_MIN']
add_alt_abbreviations('short',['shrt']) #: appears in ['SHRT_MAX', 'SHRT_MIN']
add_alt_abbreviations('sig abort',['sigabrt']) #: appears in ['SIGABRT']
add_alt_abbreviations('signal abort',['sigabrt']) #: appears in ['SIGABRT']
add_alt_abbreviations('sig F. P. E.',['sigfpe']) #: appears in ['SIGFPE']
add_alt_abbreviations('signal F. P. E.',['sigfpe']) #: appears in ['SIGFPE']
add_alt_abbreviations('sig ill',['sigill']) #: appears in ['SIGILL']
add_alt_abbreviations('sig illegal',['sigill']) #: appears in ['SIGILL']
add_alt_abbreviations('signal ill',['sigill']) #: appears in ['SIGILL']
add_alt_abbreviations('signal illegal',['sigill']) #: appears in ['SIGILL']
add_alt_abbreviations('sig int',['sigint']) #: appears in ['SIGINT']
add_alt_abbreviations('sig interrupt',['sigint']) #: appears in ['SIGINT']
add_alt_abbreviations('signal int',['sigint']) #: appears in ['SIGINT']
add_alt_abbreviations('signal interrupt',['sigint']) #: appears in ['SIGINT']
add_alt_abbreviations('sig seg V.',['sigsegv']) #: appears in ['SIGSEGV']
add_alt_abbreviations('sig segment V.',['sigsegv']) #: appears in ['SIGSEGV']
add_alt_abbreviations('signal seg V.',['sigsegv']) #: appears in ['SIGSEGV']
add_alt_abbreviations('signal segment violation',['sigsegv']) #: appears in ['SIGSEGV']
add_alt_abbreviations('sig term',['sigterm']) #: appears in ['SIGTERM']
add_alt_abbreviations('sig terminal',['sigterm']) #: appears in ['SIGTERM']
add_alt_abbreviations('signal term',['sigterm']) #: appears in ['SIGTERM']
add_alt_abbreviations('signal terminal',['sigterm']) #: appears in ['SIGTERM']
add_alt_abbreviations('sinch',['sinh']) #: appears in ['sinh']
add_alt_abbreviations('sine H.',['sinh']) #: appears in ['sinh']
add_alt_abbreviations('hyperbolic sine',['sinh']) #: appears in ['sinh']
add_alt_abbreviations('size type',['size_t'])
add_alt_abbreviations('skip W. S.',['skipws']) #: appears in ['skipws']
add_alt_abbreviations('skip white space',['skipws']) #: appears in ['skipws']
add_alt_abbreviations('S. next C.',['snextc']) #: appears in ['snextc']
add_alt_abbreviations('stream next C.',['snextc']) #: appears in ['snextc']
add_alt_abbreviations('stream next char',['snextc']) #: appears in ['snextc']
add_alt_abbreviations('sprint F.',['sprintf']) #: appears in ['sprintf']
add_alt_abbreviations('S. print F.',['sprintf']) #: appears in ['sprintf']
add_alt_abbreviations('string print F.',['sprintf']) #: appears in ['sprintf']
add_alt_abbreviations('string print format',['sprintf']) #: appears in ['sprintf']
add_alt_abbreviations('S. put back C.',['sputbackc']) #: appears in ['sputbackc']
add_alt_abbreviations('stream put back C.',['sputbackc']) #: appears in ['sputbackc']
add_alt_abbreviations('stream put back char',['sputbackc']) #: appears in ['sputbackc']
add_alt_abbreviations('S. put back char',['sputbackc']) #: appears in ['sputbackc']
add_alt_abbreviations('S. put C.',['sputc']) #: appears in ['sputc']
add_alt_abbreviations('S. put char',['sputc']) #: appears in ['sputc']
add_alt_abbreviations('stream put C.',['sputc']) #: appears in ['sputc']
add_alt_abbreviations('stream put char',['sputc']) #: appears in ['sputc']
add_alt_abbreviations('S. put N.',['sputn']) #: appears in ['sputn']
add_alt_abbreviations('stream put N.',['sputn']) #: appears in ['sputn']
add_alt_abbreviations('sqirt',['sqrt']) #: appears in ['sqrt']
add_alt_abbreviations('square root',['sqrt']) #: appears in ['sqrt']
add_alt_abbreviations('S. rand',['srand']) #: appears in ['srand']
add_alt_abbreviations('S. random',['srand']) #: appears in ['srand']
add_alt_abbreviations('seed rand',['srand']) #: appears in ['srand']
add_alt_abbreviations('seed random',['srand']) #: appears in ['srand']
add_alt_abbreviations('S. scan F.',['sscanf']) #: appears in ['sscanf']
add_alt_abbreviations('string scan F.',['sscanf']) #: appears in ['sscanf']
add_alt_abbreviations('S. scan format',['sscanf']) #: appears in ['sscanf']
add_alt_abbreviations('string scan format',['sscanf']) #: appears in ['sscanf']
add_alt_abbreviations('S. T. D. arg',['stdarg']) #: appears in ['stdarg']
add_alt_abbreviations('S. T. D. argument',['stdarg']) #: appears in ['stdarg']
add_alt_abbreviations('standard arg',['stdarg']) #: appears in ['stdarg']
add_alt_abbreviations('standard argument',['stdarg']) #: appears in ['stdarg']
add_alt_abbreviations('S. T. D. deaf',['stddef']) #: appears in ['stddef']
add_alt_abbreviations('standard deaf',['stddef']) #: appears in ['stddef']
add_alt_abbreviations('S. T. D. definitions',['stddef']) #: appears in ['stddef']
add_alt_abbreviations('standard definitions',['stddef']) #: appears in ['stddef']
add_alt_abbreviations('S. T. D. error',['stderr']) #: appears in ['stderr']
add_alt_abbreviations('standard error',['stderr']) #: appears in ['stderr']
add_alt_abbreviations('studio',['stdio']) #: appears in ['stdio', 'sync_with_stdio']
add_alt_abbreviations('S. T. D. I. O.',['stdio']) #: appears in ['stdio', 'sync_with_stdio']
add_alt_abbreviations('standard I. O.',['stdio']) #: appears in ['stdio', 'sync_with_stdio']
add_alt_abbreviations('S. T. D. lib',['stdlib']) #: appears in ['stdlib']
add_alt_abbreviations('S. T. D. library',['stdlib']) #: appears in ['stdlib']
add_alt_abbreviations('standard lib',['stdlib']) #: appears in ['stdlib']
add_alt_abbreviations('standard library',['stdlib']) #: appears in ['stdlib']
add_alt_abbreviations('S. T. D. out',['stdout']) #: appears in ['stdout']
add_alt_abbreviations('standard out',['stdout']) #: appears in ['stdout']
add_alt_abbreviations('stir cat',['strcat']) #: appears in ['strcat']
add_alt_abbreviations('stir concat',['strcat']) #: appears in ['strcat']
add_alt_abbreviations('stir concatenate',['strcat']) #: appears in ['strcat']
add_alt_abbreviations('string cat',['strcat']) #: appears in ['strcat']
add_alt_abbreviations('string concat',['strcat']) #: appears in ['strcat']
add_alt_abbreviations('string concatenate',['strcat']) #: appears in ['strcat']
add_alt_abbreviations('stir Chir',['strchr']) #: appears in ['strchr']
add_alt_abbreviations('string Chir',['strchr']) #: appears in ['strchr']
add_alt_abbreviations('stir char',['strchr']) #: appears in ['strchr']
add_alt_abbreviations('string char',['strchr']) #: appears in ['strchr']
add_alt_abbreviations('stir character',['strchr']) #: appears in ['strchr']
add_alt_abbreviations('string character',['strchr']) #: appears in ['strchr']
add_alt_abbreviations('stir comp',['strcmp']) #: appears in ['strcmp']
add_alt_abbreviations('stir compare',['strcmp']) #: appears in ['strcmp']
add_alt_abbreviations('string comp',['strcmp']) #: appears in ['strcmp']
add_alt_abbreviations('string compare',['strcmp']) #: appears in ['strcmp']
add_alt_abbreviations('stir call',['strcoll']) #: appears in ['strcoll']
add_alt_abbreviations('string call',['strcoll']) #: appears in ['strcoll']
add_alt_abbreviations('stir collate',['strcoll']) #: appears in ['strcoll']
add_alt_abbreviations('string collate',['strcoll']) #: appears in ['strcoll']
add_alt_abbreviations('stir copy',['strcpy']) #: appears in ['strcpy']
add_alt_abbreviations('stir C. P. Y.',['strcpy']) #: appears in ['strcpy']
add_alt_abbreviations('string copy',['strcpy']) #: appears in ['strcpy']
add_alt_abbreviations('string C. P. Y.',['strcpy']) #: appears in ['strcpy']
add_alt_abbreviations('stir C. span',['strcspn']) #: appears in ['strcspn']
add_alt_abbreviations('stir complementary span',['strcspn']) #: appears in ['strcspn']
add_alt_abbreviations('string complementary span',['strcspn']) #: appears in ['strcspn']
add_alt_abbreviations('stir error',['strerror']) #: appears in ['strerror']
add_alt_abbreviations('string error',['strerror']) #: appears in ['strerror']
add_alt_abbreviations('stir F. time',['strftime']) #: appears in ['strftime']
add_alt_abbreviations('string F. time',['strftime']) #: appears in ['strftime']
add_alt_abbreviations('stir format time',['strftime']) #: appears in ['strftime']
add_alt_abbreviations('string format time',['strftime']) #: appears in ['strftime']
add_alt_abbreviations('string buff',['stringbuf']) #: appears in ['stringbuf']
add_alt_abbreviations('string buffer',['stringbuf']) #: appears in ['stringbuf']
add_alt_abbreviations('string stream',['stringstream']) #: appears in ['stringstream']
add_alt_abbreviations('stir Len',['strlen']) #: appears in ['strlen']
add_alt_abbreviations('string Len',['strlen']) #: appears in ['strlen']
add_alt_abbreviations('stir length',['strlen']) #: appears in ['strlen']
add_alt_abbreviations('string length',['strlen']) #: appears in ['strlen']
add_alt_abbreviations('stern cat',['strncat']) #: appears in ['strncat']
add_alt_abbreviations('string N. cat',['strncat']) #: appears in ['strncat']
add_alt_abbreviations('string N. concat',['strncat']) #: appears in ['strncat']
add_alt_abbreviations('string N. concatenate',['strncat']) #: appears in ['strncat']
add_alt_abbreviations('stern comp',['strncmp']) #: appears in ['strncmp']
add_alt_abbreviations('string N. comp',['strncmp']) #: appears in ['strncmp']
add_alt_abbreviations('string N. compare',['strncmp']) #: appears in ['strncmp']
add_alt_abbreviations('stern copy',['strncpy']) #: appears in ['strncpy']
add_alt_abbreviations('string N. copy',['strncpy']) #: appears in ['strncpy']
add_alt_abbreviations('strip bark',['strpbrk']) #: appears in ['strpbrk']
add_alt_abbreviations('strip break',['strpbrk']) #: appears in ['strpbrk']
add_alt_abbreviations('string P. break',['strpbrk']) #: appears in ['strpbrk']
add_alt_abbreviations('string pointer break',['strpbrk']) #: appears in ['strpbrk']
add_alt_abbreviations('stir Chir',['strrchr']) #: appears in ['strrchr']
add_alt_abbreviations('string archer',['strrchr']) #: appears in ['strrchr']
add_alt_abbreviations('stir R. char',['strrchr']) #: appears in ['strrchr']
add_alt_abbreviations('string R. char',['strrchr']) #: appears in ['strrchr']
add_alt_abbreviations('stir R. character',['strrchr']) #: appears in ['strrchr']
add_alt_abbreviations('string R. character',['strrchr']) #: appears in ['strrchr']
add_alt_abbreviations('stir reverse char',['strrchr']) #: appears in ['strrchr']
add_alt_abbreviations('string reverse char',['strrchr']) #: appears in ['strrchr']
add_alt_abbreviations('stir reverse character',['strrchr']) #: appears in ['strrchr']
add_alt_abbreviations('string reverse character',['strrchr']) #: appears in ['strrchr']
add_alt_abbreviations('stir span',['strspn']) #: appears in ['strspn']
add_alt_abbreviations('string span',['strspn']) #: appears in ['strspn']
add_alt_abbreviations('stir stir',['strstr']) #: appears in ['strstr']
add_alt_abbreviations('string stir',['strstr']) #: appears in ['strstr']
add_alt_abbreviations('stir string',['strstr']) #: appears in ['strstr']
add_alt_abbreviations('string string',['strstr']) #: appears in ['strstr']
add_alt_abbreviations('stir Todd',['strtod']) #: appears in ['strtod']
add_alt_abbreviations('stir to D.',['strtod']) #: appears in ['strtod']
add_alt_abbreviations('stir to double',['strtod']) #: appears in ['strtod']
add_alt_abbreviations('string to D.',['strtod']) #: appears in ['strtod']
add_alt_abbreviations('string to double',['strtod']) #: appears in ['strtod']
add_alt_abbreviations('stir talk',['strtok']) #: appears in ['strtok']
add_alt_abbreviations('stir toke',['strtok']) #: appears in ['strtok']
add_alt_abbreviations('stir token',['strtok']) #: appears in ['strtok']
add_alt_abbreviations('string toke',['strtok']) #: appears in ['strtok']
add_alt_abbreviations('string token',['strtok']) #: appears in ['strtok']
add_alt_abbreviations('stir tall',['strtol']) #: appears in ['strtol']
add_alt_abbreviations('stir to L.',['strtol']) #: appears in ['strtol']
add_alt_abbreviations('stir to long',['strtol']) #: appears in ['strtol']
add_alt_abbreviations('string to L.',['strtol']) #: appears in ['strtol']
add_alt_abbreviations('string to long',['strtol']) #: appears in ['strtol']
add_alt_abbreviations('stir tool',['strtoul']) #: appears in ['strtoul']
add_alt_abbreviations('stir to U. L.',['strtoul']) #: appears in ['strtoul']
add_alt_abbreviations('stir to unsigned long',['strtoul']) #: appears in ['strtoul']
add_alt_abbreviations('string tool',['strtoul']) #: appears in ['strtoul']
add_alt_abbreviations('string to U. L.',['strtoul']) #: appears in ['strtoul']
add_alt_abbreviations('string to unsigned long',['strtoul']) #: appears in ['strtoul']
add_alt_abbreviations('str X. form',['strxfrm']) #: appears in ['strxfrm']
add_alt_abbreviations('string X. form',['strxfrm']) #: appears in ['strxfrm']
add_alt_abbreviations('str transform',['strxfrm']) #: appears in ['strxfrm']
add_alt_abbreviations('string transform',['strxfrm']) #: appears in ['strxfrm']
add_alt_abbreviations('sun get C.',['sungetc']) #: appears in ['sungetc']
add_alt_abbreviations('stream unget C.',['sungetc']) #: appears in ['sungetc']
add_alt_abbreviations('stream unget char',['sungetc']) #: appears in ['sungetc']
add_alt_abbreviations('stream unget character',['sungetc']) #: appears in ['sungetc']
add_alt_abbreviations('tan H.',['tanh']) #: appears in ['tanh']
add_alt_abbreviations('tan hyperbolic',['tanh']) #: appears in ['tanh']
add_alt_abbreviations('hyperbolic tan',['tanh']) #: appears in ['tanh']
add_alt_abbreviations('hyperbolic tangent',['tanh']) #: appears in ['tanh']
add_alt_abbreviations('tell G.',['tellg']) #: appears in ['tellg']
add_alt_abbreviations('tell get',['tellg']) #: appears in ['tellg']
add_alt_abbreviations('tell P.',['tellp']) #: appears in ['tellp']
add_alt_abbreviations('tell put',['tellp']) #: appears in ['tellp']
add_alt_abbreviations('temp file',['tmpfile']) #: appears in ['tmpfile']
add_alt_abbreviations('temporary file',['tmpfile']) #: appears in ['tmpfile']
add_alt_abbreviations('temp name',['tmpnam']) #: appears in ['L_tmpnam', 'tmpnam']
add_alt_abbreviations('temporary name',['tmpnam']) #: appears in ['L_tmpnam', 'tmpnam']
add_alt_abbreviations('temp nam',['tmpnam']) #: appears in ['L_tmpnam', 'tmpnam']
add_alt_abbreviations('temporary nam',['tmpnam']) #: appears in ['L_tmpnam', 'tmpnam']
add_alt_abbreviations('temp name',['tmpname']) #: appears in ['tmpname']
add_alt_abbreviations('temporary name',['tmpname']) #: appears in ['tmpname']
add_alt_abbreviations('time type',['time_t'])
add_alt_abbreviations('to lower',['tolower']) #: appears in ['tolower']
add_alt_abbreviations('to lowercase',['tolower']) #: appears in ['tolower']
add_alt_abbreviations('to upper',['toupper']) #: appears in ['toupper']
add_alt_abbreviations('to uppercase',['toupper']) #: appears in ['toupper']
add_alt_abbreviations('U. char',['uchar']) #: appears in ['UCHAR_MAX']
add_alt_abbreviations('unsigned char',['uchar']) #: appears in ['UCHAR_MAX']
add_alt_abbreviations('unsigned character',['uchar']) #: appears in ['UCHAR_MAX']
add_alt_abbreviations('U. flow',['uflow']) #: appears in ['uflow']
add_alt_abbreviations('U. long',['ulong']) #: appears in ['ULONG_MAX']
add_alt_abbreviations('unsigned long',['ulong']) #: appears in ['ULONG_MAX']
add_alt_abbreviations('U. L. to A.',['ultoa']) #: appears in ['ultoa']
add_alt_abbreviations('U. L. to ascii',['ultoa']) #: appears in ['ultoa']
add_alt_abbreviations('unsigned long to A.',['ultoa']) #: appears in ['ultoa']
add_alt_abbreviations('unsigned long to ascii',['ultoa']) #: appears in ['ultoa']
add_alt_abbreviations('un get',['unget']) #: appears in ['unget']
add_alt_abbreviations('un get C.',['ungetc']) #: appears in ['ungetc']
add_alt_abbreviations('un get char',['ungetc']) #: appears in ['ungetc']
add_alt_abbreviations('un get character',['ungetc']) #: appears in ['ungetc']
add_alt_abbreviations('unit buff',['unitbuf']) #: appears in ['unitbuf']
add_alt_abbreviations('unit buffer',['unitbuf']) #: appears in ['unitbuf']
add_alt_abbreviations('un set F.',['unsetf']) #: appears in ['unsetf']
add_alt_abbreviations('un set format',['unsetf']) #: appears in ['unsetf']
add_alt_abbreviations('un set flag',['unsetf']) #: appears in ['unsetf']
add_alt_abbreviations('U. short',['ushrt']) #: appears in ['USHRT_MAX']
add_alt_abbreviations('unsigned short',['ushrt']) #: appears in ['USHRT_MAX']
add_alt_abbreviations('V. A.',['va']) #: appears in ['va_arg', 'va_end', 'va_list', 'va_start']
add_alt_abbreviations('var arg',['va']) #: appears in ['va_arg', 'va_end', 'va_list', 'va_start']
add_alt_abbreviations('V. F. print F.',['vfprintf']) #: appears in ['vfprintf']
add_alt_abbreviations('V. file print F.',['vfprintf']) #: appears in ['vfprintf']
add_alt_abbreviations('V. file print format',['vfprintf']) #: appears in ['vfprintf']
add_alt_abbreviations('var F. print F.',['vfprintf']) #: appears in ['vfprintf']
add_alt_abbreviations('var file print F.',['vfprintf']) #: appears in ['vfprintf']
add_alt_abbreviations('var file print format',['vfprintf']) #: appears in ['vfprintf']
add_alt_abbreviations('V. print F.',['vprintf']) #: appears in ['vprintf']
add_alt_abbreviations('V. print format',['vprintf']) #: appears in ['vprintf']
add_alt_abbreviations('var print F.',['vprintf']) #: appears in ['vprintf']
add_alt_abbreviations('var print format',['vprintf']) #: appears in ['vprintf']
add_alt_abbreviations('V. S. print F.',['vsprintf']) #: appears in ['vsprintf']
add_alt_abbreviations('V. string print F.',['vsprintf']) #: appears in ['vsprintf']
add_alt_abbreviations('V. string print format',['vsprintf']) #: appears in ['vsprintf']
add_alt_abbreviations('var S. print F.',['vsprintf']) #: appears in ['vsprintf']
add_alt_abbreviations('var string print F.',['vsprintf']) #: appears in ['vsprintf']
add_alt_abbreviations('var string print format',['vsprintf']) #: appears in ['vsprintf']
add_alt_abbreviations('W. day',['wday']) #: appears in ['tm_wday']
add_alt_abbreviations('weekday',['wday']) #: appears in ['tm_wday']
add_alt_abbreviations('X. Alloc',['xalloc']) #: appears in ['xalloc']
add_alt_abbreviations('extensible Alloc',['xalloc']) #: appears in ['xalloc']
add_alt_abbreviations('X. allocate',['xalloc']) #: appears in ['xalloc']
add_alt_abbreviations('extensible allocate',['xalloc']) #: appears in ['xalloc']
add_alt_abbreviations('X. S. get N.',['xsgetn']) #: appears in ['xsgetn']
add_alt_abbreviations('X. stream get N.',['xsgetn']) #: appears in ['xsgetn']
add_alt_abbreviations('X. S. put N.',['xsputn']) #: appears in ['xsputn']
add_alt_abbreviations('X. stream put N.',['xsputn']) #: appears in ['xsputn']
add_alt_abbreviations('Y. day',['yday']) #: appears in ['tm_yday']
add_alt_abbreviations('year day',['yday']) #: appears in ['tm_yday']

# malloc, alloc!

# add_pronunciation('py']), 'pie')
# add_acronym('py']))














