##############################################################################
# VoiceCode, a programming-by-voice environment
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# (C)2000, National Research Council of Canada
#
##############################################################################


add_alt_abbreviations('absolute', ['abs'])
add_alt_abbreviations('address', ['addr'])
add_alt_abbreviations('alpha numeric', ['alnum'])
add_alt_abbreviations('alternate', ['alt'])
add_alt_abbreviations('alternative', ['alt'])
add_alt_abbreviations('arc tangent', ['atan'])
add_alt_abbreviations('argument', ['arg'])
add_alt_abbreviations('argument count', ['argc'])
add_alt_abbreviations('arg C.', ['argc'])
add_alt_abbreviations('argument value', ['argv'])
add_alt_abbreviations('arg V.', ['argv'])
add_alt_abbreviations('asynchronous', ['asyn', 'async'])
add_alt_abbreviations('attribute', ['attr'])
add_alt_abbreviations('available', ['avail'])
add_alt_abbreviations('average', ['avg'])

add_alt_abbreviations('begin', ['beg'])
add_alt_abbreviations('beginning', ['beg'])
add_alt_abbreviations('block', ['blk'])
add_alt_abbreviations('blocking', ['blk'])
add_alt_abbreviations('buffer', ['buf', 'buff'])
add_alt_abbreviations('built in', ['builtin'])

add_alt_abbreviations('calculate', ['calc'])
add_alt_abbreviations('calculated', ['calc'])
add_alt_abbreviations('calculation', ['calc'])
add_alt_abbreviations('callback', ['cbk'])
add_alt_abbreviations('change', ['chg'])
add_alt_abbreviations('changed', ['chg'])
add_alt_abbreviations('character', ['char', 'chr'])
add_alt_abbreviations('clear', ['clr'])
add_alt_abbreviations('column', ['col'])
add_alt_abbreviations('command', ['cmd'])
add_alt_abbreviations('compare', ['cmp'])
add_alt_abbreviations('C. plus plus', ['cpp'])
add_alt_abbreviations('concatenate', ['concat'])
add_alt_abbreviations('condition', ['cond'])
add_alt_abbreviations('configuration', ['conf', 'config'])
add_alt_abbreviations('configure', ['conf', 'config'])
add_alt_abbreviations('connected', ['conn'])
add_alt_abbreviations('content', ['cont'])
add_alt_abbreviations('context', ['cont'])
add_alt_abbreviations('control', ['ctrl', 'cntrl', 'ctl'])
add_alt_abbreviations('cosine', ['cos'])
add_alt_abbreviations('current', ['curr', 'cur'])
add_alt_abbreviations('cursor', ['cur'])

add_alt_abbreviations('data base', ['db'])
add_alt_abbreviations('declaration', ['decl'])
add_alt_abbreviations('declare', ['decl'])
add_alt_abbreviations('default', ['def'])
add_alt_abbreviations('define', ['def'])
add_alt_abbreviations('defined', ['def'])
add_alt_abbreviations('definition', ['def'])
add_alt_abbreviations('delimiter', ['delim'])
add_alt_abbreviations('device', ['dev'])
add_alt_abbreviations('dictionary', ['dict'])
add_alt_abbreviations('direction', ['dir'])
add_alt_abbreviations('directory', ['dir'])
add_alt_abbreviations('distance', ['dst'])
add_alt_abbreviations('divide', ['div'])
add_alt_abbreviations('document', ['doc'])
add_alt_abbreviations('documentation', ['doc'])
add_alt_abbreviations('domain', ['dom'])

add_alt_abbreviations('element', ['elem'])
add_alt_abbreviations('entry', ['ent'])
add_alt_abbreviations('entity', ['ent'])
add_alt_abbreviations('environment', ['env', 'environ'])
add_alt_abbreviations('end of line', ['eol'])
add_alt_abbreviations('E. val', ['eval'])
add_alt_abbreviations('evaluate', ['eval'])
add_alt_abbreviations('evaluation', ['eval'])
add_alt_abbreviations('exception', ['exc'])
add_alt_abbreviations('exclusive or', ['xor'])
add_alt_abbreviations('executable', ['exec'])
add_alt_abbreviations('execute', ['exec'])
add_alt_abbreviations('example', ['ex'])
add_alt_abbreviations('expression', ['expr'])

add_alt_abbreviations('fie foe', ['fifo'])
add_alt_abbreviations('first in first out', ['fifo'])
add_alt_abbreviations('format', ['fmt'])
add_alt_abbreviations('function', ['func', 'fct'])
add_alt_abbreviations('fraction', ['frac'])

add_alt_abbreviations('general', ['gen'])
add_alt_abbreviations('generic', ['gen'])
add_alt_abbreviations('global', ['glob'])
add_alt_abbreviations('go to', ['goto'])
add_alt_abbreviations('group I. D.', ['gid'])

add_alt_abbreviations('hexadecimal', ['hex'])
add_alt_abbreviations('horizontal', ['horiz'])
add_alt_abbreviations('horizontally', ['horiz'])

add_alt_abbreviations('I. map', ['imap'])
add_alt_abbreviations('implementation', ['impl'])
add_alt_abbreviations('include', ['inc', 'incl'])
add_alt_abbreviations('included', ['incl'])
add_alt_abbreviations('increment', ['inc'])
add_alt_abbreviations('initial', ['init'])
add_alt_abbreviations('initialize', ['init'])
add_alt_abbreviations('insert', ['ins'])
add_alt_abbreviations('input output', ['io'])
add_alt_abbreviations('information', ['info'])
add_alt_abbreviations('integer', ['int'])
add_alt_abbreviations('interpreter', ['interp'])
add_alt_abbreviations('introduction', ['intro'])

add_alt_abbreviations('length', ['len'])
add_alt_abbreviations('line', ['ln'])
add_alt_abbreviations('link', ['lnk'])
add_alt_abbreviations('location', ['loc'])
add_alt_abbreviations('locate', ['loc'])
add_alt_abbreviations('log in', ['login'])

add_alt_abbreviations('make', ['mk'])
add_alt_abbreviations('maximum', ['max'])
add_alt_abbreviations('memory', ['mem'])
add_alt_abbreviations('message', ['msg'])
add_alt_abbreviations('millisecond', ['msec'])
add_alt_abbreviations('minimum', ['min'])
add_alt_abbreviations('modify', ['mod'])
add_alt_abbreviations('modified', ['mod'])
add_alt_abbreviations('mount', ['mnt'])
add_alt_abbreviations('mounted', ['mnt'])
# py_std (not really... it's a Unix thing and it's used in all kinds of
# libraries and languages. -- AD)
add_alt_abbreviations('M. time', ['mtime'])

add_alt_abbreviations('number', ['no', 'num'])

add_alt_abbreviations('object', ['obj'])
add_alt_abbreviations('octal', ['oct'])
add_alt_abbreviations('optimize', ['opt'])
add_alt_abbreviations('option', ['opt'])
add_alt_abbreviations('optional', ['opt'])


add_alt_abbreviations('operating system', ['os'])

add_alt_abbreviations('package', ['pkg'])
add_alt_abbreviations('parameter', ['par', 'param'])
add_alt_abbreviations('pattern', ['pat', 'patt'])
add_alt_abbreviations('position', ['pos'])
add_alt_abbreviations('position', ['posn'])
add_alt_abbreviations('permission', ['perm'])
add_alt_abbreviations('positioning', ['pos'])
add_alt_abbreviations('previous', ['prev'])
add_alt_abbreviations('professional', ['prof'])
add_alt_abbreviations('profile', ['prof'])
add_alt_abbreviations('profiling', ['prof'])
add_alt_abbreviations('protocol', ['proto'])
add_alt_abbreviations('prototype', ['proto'])
add_alt_abbreviations('punctuation', ['punc', 'punct'])

add_alt_abbreviations('quotient', ['quot'])

add_alt_abbreviations('random', ['rand'])
add_alt_abbreviations('read', ['rd'])
add_alt_abbreviations('rectangle', ['rect'])
add_alt_abbreviations('reference', ['ref'])
add_alt_abbreviations('regular', ['reg'])
add_alt_abbreviations('regular expression', ['regexp', 'regex', 'reg', 'rexp'])
add_alt_abbreviations('relative', ['rel'])
add_alt_abbreviations('remove', ['rm'])
add_alt_abbreviations('represent', ['repr'])
add_alt_abbreviations('representation', ['repr'])
add_alt_abbreviations('request', ['req'])

add_alt_abbreviations('screen', ['scr'])
add_alt_abbreviations('second', ['sec'])
add_alt_abbreviations('separator', ['sep'])
add_alt_abbreviations('sequence', ['seq'])
add_alt_abbreviations('server', ['serv', 'srv'])
add_alt_abbreviations('service', ['srv'])
add_alt_abbreviations('signal', ['sig'])
add_alt_abbreviations('sine', ['sin'])
add_alt_abbreviations('socket', ['sock'])
add_alt_abbreviations('sound X.', ['soundex'])
add_alt_abbreviations('source', ['src'])
add_alt_abbreviations('space', ['spc'])
add_alt_abbreviations('S. T. D. in', ['stdin'])
add_alt_abbreviations('standard in', ['stdin'])
add_alt_abbreviations('standard input', ['stdin'])
add_alt_abbreviations('standard', ['std'])
add_alt_abbreviations('static', ['stat'])
add_alt_abbreviations('statistics', ['stat'])
add_alt_abbreviations('string', ['str'])
add_alt_abbreviations('sub routine', ['sub'])
add_alt_abbreviations('symbol', ['sym'])
add_alt_abbreviations('synchronize', ['sync'])
add_alt_abbreviations('synchronous', ['sync'])
add_alt_abbreviations('system', ['sys'])

add_alt_abbreviations('temporary', ['temp', 'tmp'])
add_alt_abbreviations('term I. D.', ['termid'])
add_alt_abbreviations('test', ['tst'])
add_alt_abbreviations('terminal I. D.', ['termid'])
add_alt_abbreviations('token', ['tok'])
add_alt_abbreviations('transform', ['trans'])
add_alt_abbreviations('transformation', ['trans'])
add_alt_abbreviations('transition', ['trans'])
add_alt_abbreviations('translation', ['trans'])
add_alt_abbreviations('transport', ['trans'])

# as in UU encoding
add_alt_abbreviations('user I. D.', ['uid'])
add_alt_abbreviations('undefine', ['undef'])
add_alt_abbreviations('undefined', ['undef'])

add_alt_abbreviations('value', ['val'])
add_alt_abbreviations('variable', ['var'])
add_alt_abbreviations('vertical', ['vert'])
add_alt_abbreviations('vertically', ['vert'])

add_alt_abbreviations('window', ['win'])

add_alt_abbreviations('X. or', ['xor'])

add_pronunciation('def', 'deaf')
add_acronym('cgi')
add_acronym('db')
add_acronym('dtd')
add_acronym('eol')
add_acronym('gid')
add_acronym('html')
add_acronym('http')
add_acronym('io')
add_acronym('ip')
add_acronym('nntp')
add_acronym('os')
add_acronym('osf')
add_acronym('pty')
add_acronym('rgb')
add_acronym('smtp')
add_acronym('tty')
add_acronym('uid')
add_acronym('url')
add_acronym('uu')
add_acronym('xml')
